user                    www-data;
worker_processes        auto;
error_log               /var/log/nginx/error.log;
pid                     /var/run/nginx.pid;
include                 /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections  1024;
    use                 epoll;
    multi_accept        on;
}

http {
    # TODO
    #log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    #            '$status $body_bytes_sent "$http_referer" '
    #            '"$http_user_agent" "$http_x_forwarded_for" '
    #            '"$http_x_real_ip" $request_time $upstream_addr $upstream_response_time';
    access_log      /var/log/nginx/access.log;

    include         mime.types;
    default_type    application/octet-stream;

    sendfile      on;
    tcp_nopush    on;
    tcp_nodelay   on;

    map_hash_bucket_size        128;

    client_header_timeout       3m;
    client_body_timeout         3m;
    client_max_body_size        256m;
    client_header_buffer_size   4k;
    client_body_buffer_size     256k;
    large_client_header_buffers 4 32k;

    send_timeout                    3m;
    keepalive_timeout               60 60;
    reset_timedout_connection       on;
    server_names_hash_max_size      1024;
    server_names_hash_bucket_size   1024;
    ignore_invalid_headers          on;
    connection_pool_size            256;
    request_pool_size               4k;
    output_buffers                  4 32k;
    postpone_output                 1460;

    # Compression gzip
    gzip on;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";
    gzip_proxied any;
    gzip_min_length 512;
    gzip_comp_level 6;
    gzip_buffers 8 64k;
    gzip_types text/plain text/xml text/css text/js application/x-javascript application/xml image/png image/x-icon image/gif image/jpeg image/svg+xml application/xml+rss text/javascript application/atom+xml application/javascript application/json application/x-font-ttf font/opentype;

    # Proxy settings
    proxy_redirect          off;
    proxy_http_version      1.1;
    proxy_set_header        Host            $host;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        Upgrade $http_upgrade;
    proxy_set_header        Connection 'upgrade';
    proxy_pass_header       Set-Cookie;
    proxy_connect_timeout   150;
    proxy_send_timeout      150;
    proxy_read_timeout      150;
    proxy_buffering         on;
    proxy_buffers           4 1024k;
    proxy_buffer_size       128k;
    proxy_busy_buffers_size 1024k;

    # fastcgi_buffers       5 1024k;
    # fastcgi_buffer_size   1024k;

    server_tokens           off;

    include /etc/nginx/conf.d/*.conf;
}
